export * from './Banks'
export * from './Franchises'
export * from './Home'
export * from './Hospitals'
export * from './LoginForm'
export * from './Pumps'
export * from './Saloons'
export * from './SignupForm'
export * from './Splash'
// export * from './'